version: "3.7"

services:
  app:
    image: ghcr.io/duff89/parser_avito:latest
    container_name: wentfox-avito-parser
    restart: unless-stopped
    stop_grace_period: 1m

    volumes:
      - ${APP_DATA_DIR}/data:/data

    environment:
      - TZ=Europe/Berlin

    entrypoint: ["/bin/bash", "-c"]
    command: |
      set -e

      mkdir -p /data/result

      if [ ! -f /data/cookies.json ]; then
        echo "{}" > /data/cookies.json
      fi

      if [ ! -f /data/database.db ]; then
        touch /data/database.db
      fi

      if [ ! -f /data/config.toml ]; then
        cat > /data/config.toml <<'EOF'
      [avito]
      tg_token = ""
      tg_chat_id = []

      vk_token = ""
      vk_user_id = []

      urls = [
        "https://www.avito.ru/all?q=raspberry+pi"
      ]

      count = 1

      keys_word_white_list = []
      keys_word_black_list = []
      seller_black_list = []

      max_price = 99999999
      min_price = 0
      geo = ""

      proxy_string = ""
      proxy_change_url = ""

      pause_general = 60
      pause_between_links = 10

      max_age = 0
      max_count_of_retry = 5

      ignore_reserv = true
      ignore_promotion = false

      one_time_start = false
      one_file_for_link = false

      parse_views = false
      save_xlsx = true

      use_webdriver = false
      use_bypass_api = false
      cookies_api_key = ""
      use_own_cookies = false

      parse_phone = false
      proxy_notifier = ""
      tg_only_text = false

      retry_delay = 5
      timeout = 20
      block_threshold = 3
      EOF
      fi

      rm -f /app/config.toml
      rm -f /app/cookies.json
      rm -f /app/database.db
      rm -rf /app/result

      ln -s /data/config.toml /app/config.toml
      ln -s /data/cookies.json /app/cookies.json
      ln -s /data/database.db /app/database.db
      ln -s /data/result /app/result

      cd /app
      python parser_cls.py
