version: "3.7"

services:
  app:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    restart: unless-stopped
    ports:
      - "2053:2053"
      - "7443:7443"
    volumes:
      - ${APP_DATA_DIR}/data:/etc/x-ui
    environment:
      - TZ=Europe/Berlin
