version: "3.7"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: mtproto_panel
      POSTGRES_USER: mtproto
      POSTGRES_PASSWORD: mtproto
    volumes:
      - ${APP_DATA_DIR}/pgdata:/var/lib/postgresql/data

  backend:
    build: 
      # Добавили :backend в конце, чтобы Docker сразу зашел в нужную папку
      context: https://github.com/danielVNru/mtproto-panel.git#master:backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PORT: "3000"
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: mtproto_panel
      DB_USER: mtproto
      DB_PASSWORD: mtproto
      JWT_SECRET: "wentfox_secret_key_123"
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "admin"

  frontend:
    build: 
      # Аналогично добавили :frontend для фронта
      context: https://github.com/danielVNru/mtproto-panel.git#master:frontend
    restart: unless-stopped
    ports:
      - "8085:80"
    depends_on:
      - backend
